"""
Script Name: 02_euclidean_distance.py
Description: Automates the calculation of a Euclidean Distance raster surface 
             (proximity to nearest road) using ArcPy and the Spatial Analyst extension.
"""

import os
import arcpy

def check_spatial_license():
    """Validates and securely checks out the ArcGIS Spatial Analyst extension."""
    if arcpy.CheckExtension("Spatial") == "Available":
        arcpy.CheckOutExtension("Spatial")
        arcpy.AddMessage("Spatial Analyst extension checked out successfully.")
    else:
        raise arcpy.ExecuteError("Spatial Analyst license is unavailable. Execution halted.")

def calculate_proximity(input_roads, output_raster, max_distance, cell_size):
    """Executes the Euclidean Distance tool with robust error handling."""
    try:
        # 1. Initialize environment and extension
        check_spatial_license()
        arcpy.env.overwriteOutput = True

        arcpy.AddMessage(f"Initializing Euclidean Distance calculation for: {input_roads}...")

        # 2. Core Geoprocessing Execution (Mapped exactly to your original parameters)
        arcpy.gp.EucDistance_sa(
            input_roads,
            output_raster,
            max_distance,       # Maximum distance (200)
            cell_size,          # Output cell size
            "",                 # Out direction raster (Left blank intentionally)
            "PLANAR",           # Distance Method
            "",                 # Out back direction raster
            ""                  # Out source direction raster
        )

        arcpy.AddMessage(f"SUCCESS: Distance surface saved to {output_raster}")

    except arcpy.ExecuteError:
        # Log specific ArcGIS geoprocessing errors
        arcpy.AddError("ArcPy Geoprocessing Error: " + arcpy.GetMessages(2))
    except Exception as e:
        # Log unexpected Python system/logic errors
        arcpy.AddError(f"Unexpected Script Error: {str(e)}")
    finally:
        # 3. Prevent license locking by always returning it to the pool
        arcpy.CheckInExtension("Spatial")
        arcpy.AddMessage("Spatial Analyst extension checked back in.")

if __name__ == "__main__":
    # Standardizing paths dynamically for GitHub reproducibility
    current_directory = os.path.dirname(os.path.abspath(__file__))
    gdb_path = os.path.join(current_directory, "Data", "Default.gdb")

    # Ensure output directory exists for users cloning the repo
    if not os.path.exists(os.path.dirname(gdb_path)):
        os.makedirs(os.path.dirname(gdb_path))

    # Parameters mapped from your original ArcMap export
    INPUT_LAYER = "Roads2_Clip1"  # Matches the view generated by the SQL script
    OUTPUT_RASTER = os.path.join(gdb_path, "EucDist_Road5")
    MAX_DISTANCE = "200"
    CELL_SIZE = "4.73596089616185"

    # Execute main workflow
    calculate_proximity(INPUT_LAYER, OUTPUT_RASTER, MAX_DISTANCE, CELL_SIZE)
